/*
  BLOODCHAIN - Tao bang du lieu
  Thu tu chay:
  1. 00_schema.sql
  2. 02_auth_permissions.sql

  Giai thich nhanh:
  - PRIMARY KEY: khoa chinh, ma duy nhat cua bang
  - FOREIGN KEY: khoa ngoai, lien ket sang bang khac
*/

IF OBJECT_ID('dbo.vw_XuatKhoChiTiet', 'V') IS NOT NULL DROP VIEW dbo.vw_XuatKhoChiTiet;
IF OBJECT_ID('dbo.vw_PhieuYeuCauChiTiet', 'V') IS NOT NULL DROP VIEW dbo.vw_PhieuYeuCauChiTiet;
IF OBJECT_ID('dbo.vw_MauSapHetHan', 'V') IS NOT NULL DROP VIEW dbo.vw_MauSapHetHan;
IF OBJECT_ID('dbo.vw_TonKhoMau', 'V') IS NOT NULL DROP VIEW dbo.vw_TonKhoMau;
GO

IF OBJECT_ID('dbo.trg_UpdateHang', 'TR') IS NOT NULL DROP TRIGGER dbo.trg_UpdateHang;
IF OBJECT_ID('dbo.trg_TruDiem', 'TR') IS NOT NULL DROP TRIGGER dbo.trg_TruDiem;
IF OBJECT_ID('dbo.trg_CongDiem', 'TR') IS NOT NULL DROP TRIGGER dbo.trg_CongDiem;
IF OBJECT_ID('dbo.trg_UpdateTrangThaiSauXuat', 'TR') IS NOT NULL DROP TRIGGER dbo.trg_UpdateTrangThaiSauXuat;
IF OBJECT_ID('dbo.trg_Check_XuatMau', 'TR') IS NOT NULL DROP TRIGGER dbo.trg_Check_XuatMau;
IF OBJECT_ID('dbo.trg_SetHanSuDung', 'TR') IS NOT NULL DROP TRIGGER dbo.trg_SetHanSuDung;
IF OBJECT_ID('dbo.trg_Check_TachChiet', 'TR') IS NOT NULL DROP TRIGGER dbo.trg_Check_TachChiet;
GO

IF OBJECT_ID('dbo.fn_KiemTraThanhPhanKhaDung', 'FN') IS NOT NULL DROP FUNCTION dbo.fn_KiemTraThanhPhanKhaDung;
IF OBJECT_ID('dbo.fn_XepHangThanhVien', 'FN') IS NOT NULL DROP FUNCTION dbo.fn_XepHangThanhVien;
IF OBJECT_ID('dbo.fn_DiemCongTheoTheTich', 'FN') IS NOT NULL DROP FUNCTION dbo.fn_DiemCongTheoTheTich;
IF OBJECT_ID('dbo.fn_SoNgayConLai', 'FN') IS NOT NULL DROP FUNCTION dbo.fn_SoNgayConLai;
GO

IF OBJECT_ID('dbo.CHI_TIET_XUAT', 'U') IS NOT NULL DROP TABLE dbo.CHI_TIET_XUAT;
IF OBJECT_ID('dbo.PHIEU_XUAT', 'U') IS NOT NULL DROP TABLE dbo.PHIEU_XUAT;
IF OBJECT_ID('dbo.PHIEU_YEU_CAU', 'U') IS NOT NULL DROP TABLE dbo.PHIEU_YEU_CAU;
IF OBJECT_ID('dbo.THANH_PHAN_MAU', 'U') IS NOT NULL DROP TABLE dbo.THANH_PHAN_MAU;
IF OBJECT_ID('dbo.KET_QUA_XET_NGHIEM', 'U') IS NOT NULL DROP TABLE dbo.KET_QUA_XET_NGHIEM;
IF OBJECT_ID('dbo.GOI_MAU_TOAN_PHAN', 'U') IS NOT NULL DROP TABLE dbo.GOI_MAU_TOAN_PHAN;
IF OBJECT_ID('dbo.DANG_KY_CHIEN_DICH', 'U') IS NOT NULL DROP TABLE dbo.DANG_KY_CHIEN_DICH;
IF OBJECT_ID('dbo.QUY_DOI_DIEM', 'U') IS NOT NULL DROP TABLE dbo.QUY_DOI_DIEM;
IF OBJECT_ID('dbo.BENH_NHAN', 'U') IS NOT NULL DROP TABLE dbo.BENH_NHAN;
IF OBJECT_ID('dbo.NGUOI_HIEN', 'U') IS NOT NULL DROP TABLE dbo.NGUOI_HIEN;
IF OBJECT_ID('dbo.VI_TRI_KHO', 'U') IS NOT NULL DROP TABLE dbo.VI_TRI_KHO;
IF OBJECT_ID('dbo.NHAN_VIEN', 'U') IS NOT NULL DROP TABLE dbo.NHAN_VIEN;
IF OBJECT_ID('dbo.BENH_VIEN', 'U') IS NOT NULL DROP TABLE dbo.BENH_VIEN;
IF OBJECT_ID('dbo.CHIEN_DICH', 'U') IS NOT NULL DROP TABLE dbo.CHIEN_DICH;
IF OBJECT_ID('dbo.NHOM_MAU', 'U') IS NOT NULL DROP TABLE dbo.NHOM_MAU;
GO

CREATE TABLE NHOM_MAU (
  MaNhomMau VARCHAR(5) PRIMARY KEY,
  TenNhomMau NVARCHAR(10)
);
GO

CREATE TABLE CHIEN_DICH (
  MaChienDich VARCHAR(20) PRIMARY KEY,
  TenChienDich NVARCHAR(150),
  DiaDiem NVARCHAR(200),
  ThoiGian DATETIME,
  SoLuongDuKien INT,
  SoLuongThucTe INT
);
GO

CREATE TABLE BENH_VIEN (
  MaBV VARCHAR(20) PRIMARY KEY,
  TenBV NVARCHAR(150) NOT NULL,
  DiaChi NVARCHAR(250),
  SDT VARCHAR(15)
);
GO

CREATE TABLE NHAN_VIEN (
  MaNV VARCHAR(20) PRIMARY KEY,
  HoTen NVARCHAR(120),
  ChucVu NVARCHAR(100),
  Email VARCHAR(120)
);
GO

CREATE TABLE NGUOI_HIEN (
  MaNguoiHien VARCHAR(20) PRIMARY KEY,
  HoTen NVARCHAR(120) NOT NULL,
  NgaySinh DATE,
  GioiTinh NVARCHAR(10),
  CCCD VARCHAR(20) UNIQUE,
  SDT VARCHAR(15),
  BenhLy NVARCHAR(500),
  DiemTichLuy INT DEFAULT 0,
  HangThanhVien NVARCHAR(20) DEFAULT 'Bronze',
  MaNhomMau VARCHAR(5),
  FOREIGN KEY (MaNhomMau) REFERENCES NHOM_MAU(MaNhomMau)
);
GO

CREATE TABLE QUY_DOI_DIEM (
  MaDoiQua VARCHAR(20) PRIMARY KEY,
  TenQua NVARCHAR(150),
  NgayDoi DATETIME DEFAULT GETDATE() ,
  DiemDoi INT,
  MaNguoiHien VARCHAR(20),
  FOREIGN KEY (MaNguoiHien) REFERENCES NGUOI_HIEN(MaNguoiHien)
);
GO

CREATE TABLE VI_TRI_KHO (
  MaViTri VARCHAR(20) PRIMARY KEY,
  TenTu NVARCHAR(50),
  Ngan INT
);
GO

CREATE TABLE DANG_KY_CHIEN_DICH (
  MaChienDich VARCHAR(20),
  MaNguoiHien VARCHAR(20),
  NgayDangKy DATETIME,
  PRIMARY KEY (MaChienDich, MaNguoiHien),
  FOREIGN KEY (MaChienDich) REFERENCES CHIEN_DICH(MaChienDich),
  FOREIGN KEY (MaNguoiHien) REFERENCES NGUOI_HIEN(MaNguoiHien)
);
GO

CREATE TABLE GOI_MAU_TOAN_PHAN (
  MaGoiMau VARCHAR(20) PRIMARY KEY,
  NgayHien DATETIME DEFAULT GETDATE(),
  TheTich INT CHECK (TheTich in (250,350,450)),
  TrangThaiKiemDinh NVARCHAR(20) DEFAULT N'Chờ xét nghiệm',
  MaNguoiHien VARCHAR(20),
  MaNhomMau VARCHAR(5),
  MaChienDich VARCHAR(20),
  MaNV_ThuNhan VARCHAR(20),
  FOREIGN KEY (MaNguoiHien) REFERENCES NGUOI_HIEN(MaNguoiHien),
  FOREIGN KEY (MaNhomMau) REFERENCES NHOM_MAU(MaNhomMau),
  FOREIGN KEY (MaChienDich) REFERENCES CHIEN_DICH(MaChienDich),
  FOREIGN KEY (MaNV_ThuNhan) REFERENCES NHAN_VIEN(MaNV)
);
GO

CREATE TABLE KET_QUA_XET_NGHIEM (
  MaXetNghiem VARCHAR(20) PRIMARY KEY,
  LoaiXetNghiem NVARCHAR(100),
  KetQua NVARCHAR(20) check (KetQua in ('Dương tính','Âm tính')),
  NgayXetNghiem DATETIME,
  MaGoiMau VARCHAR(20),
  MaNV_ThucHien VARCHAR(20),
  FOREIGN KEY (MaGoiMau) REFERENCES GOI_MAU_TOAN_PHAN(MaGoiMau),
  FOREIGN KEY (MaNV_ThucHien) REFERENCES NHAN_VIEN(MaNV)
);
GO

CREATE TABLE THANH_PHAN_MAU (
  MaThanhPhan VARCHAR(20) PRIMARY KEY,
  LoaiThanhPhan NVARCHAR(30),
  TheTichThucTe INT,
  HanSuDung DATE,
  TrangThai NVARCHAR(20) DEFAULT N'Sẵn sàng',
  MaGoiMau VARCHAR(20),
  MaViTri VARCHAR(20),
  FOREIGN KEY (MaGoiMau) REFERENCES GOI_MAU_TOAN_PHAN(MaGoiMau),
  FOREIGN KEY (MaViTri) REFERENCES VI_TRI_KHO(MaViTri)
);
GO

CREATE TABLE BENH_NHAN (
  MaBenhNhan VARCHAR(20) PRIMARY KEY,
  HoTen NVARCHAR(120) NOT NULL,
  NgaySinh DATE,
  BenhAn NVARCHAR(500),
  MaNhomMau VARCHAR(5),
  MaBV VARCHAR(20),
  FOREIGN KEY (MaNhomMau) REFERENCES NHOM_MAU(MaNhomMau),
  FOREIGN KEY (MaBV) REFERENCES BENH_VIEN(MaBV)
);
GO

CREATE TABLE PHIEU_YEU_CAU (
  MaPhieuYC VARCHAR(20) PRIMARY KEY,
  NgayYeuCau DATETIME DEFAULT GETDATE(),
  LoaiThanhPhanCan NVARCHAR(30),
  SoLuongML INT,
  TrangThaiDuyet NVARCHAR(20) DEFAULT N'Chờ duyệt',
  MaBV VARCHAR(20),
  MaBenhNhan VARCHAR(20),
  MaNhomMau VARCHAR(5),
  MaNV_Duyet VARCHAR(20),
  FOREIGN KEY (MaBV) REFERENCES BENH_VIEN(MaBV),
  FOREIGN KEY (MaBenhNhan) REFERENCES BENH_NHAN(MaBenhNhan),
  FOREIGN KEY (MaNhomMau) REFERENCES NHOM_MAU(MaNhomMau),
  FOREIGN KEY (MaNV_Duyet) REFERENCES NHAN_VIEN(MaNV)
);
GO

CREATE TABLE PHIEU_XUAT (
  MaPhieuXuat VARCHAR(20) PRIMARY KEY,
  NgayXuat DATETIME DEFAULT GETDATE(),
  TongTheTich INT,
  MaPhieuYC VARCHAR(20),
  MaNV_Xuat VARCHAR(20),
  FOREIGN KEY (MaPhieuYC) REFERENCES PHIEU_YEU_CAU(MaPhieuYC),
  FOREIGN KEY (MaNV_Xuat) REFERENCES NHAN_VIEN(MaNV)
);
GO

CREATE TABLE CHI_TIET_XUAT (
  MaPhieuXuat VARCHAR(20),
  MaThanhPhan VARCHAR(20),
  KetQuaPhanUngCheo NVARCHAR(20),
  PRIMARY KEY (MaPhieuXuat, MaThanhPhan),
  FOREIGN KEY (MaPhieuXuat) REFERENCES PHIEU_XUAT(MaPhieuXuat),
  FOREIGN KEY (MaThanhPhan) REFERENCES THANH_PHAN_MAU(MaThanhPhan)
);
GO

/*
  BLOODCHAIN - Du lieu mau da gop vao schema
  Chay file 00 se tao bang va them du lieu mau co ban.
*/

INSERT INTO NHOM_MAU VALUES ('O+', N'O+');
INSERT INTO NHOM_MAU VALUES ('O-', N'O-');
INSERT INTO NHOM_MAU VALUES ('A+', N'A+');
INSERT INTO NHOM_MAU VALUES ('A-', N'A-');
INSERT INTO NHOM_MAU VALUES ('B+', N'B+');
INSERT INTO NHOM_MAU VALUES ('B-', N'B-');
INSERT INTO NHOM_MAU VALUES ('AB+', N'AB+');
INSERT INTO NHOM_MAU VALUES ('AB-', N'AB-');
GO

INSERT INTO CHIEN_DICH VALUES ('CD001', NCHAR(67) + NCHAR(104) + NCHAR(7911) + NCHAR(32) + NCHAR(110) + NCHAR(104) + NCHAR(7853) + NCHAR(116) + NCHAR(32) + NCHAR(272) + NCHAR(7887) + NCHAR(32) + NCHAR(50) + NCHAR(48) + NCHAR(50) + NCHAR(54), NCHAR(72) + NCHAR(224) + NCHAR(32) + NCHAR(78) + NCHAR(7897) + NCHAR(105), '2026-02-15 08:00:00', 300, 248);
INSERT INTO CHIEN_DICH VALUES ('CD002', NCHAR(71) + NCHAR(105) + NCHAR(7885) + NCHAR(116) + NCHAR(32) + NCHAR(104) + NCHAR(7891) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(109) + NCHAR(249) + NCHAR(97) + NCHAR(32) + NCHAR(104) + NCHAR(232), NCHAR(72) + NCHAR(7885) + NCHAR(99) + NCHAR(32) + NCHAR(118) + NCHAR(105) + NCHAR(7879) + NCHAR(110) + NCHAR(32) + NCHAR(84) + NCHAR(224) + NCHAR(105) + NCHAR(32) + NCHAR(99) + NCHAR(104) + NCHAR(237) + NCHAR(110) + NCHAR(104), '2026-05-10 07:30:00', 200, 126);
GO

INSERT INTO BENH_VIEN VALUES ('BV001', NCHAR(66) + NCHAR(7879) + NCHAR(110) + NCHAR(104) + NCHAR(32) + NCHAR(118) + NCHAR(105) + NCHAR(7879) + NCHAR(110) + NCHAR(32) + NCHAR(66) + NCHAR(7841) + NCHAR(99) + NCHAR(104) + NCHAR(32) + NCHAR(77) + NCHAR(97) + NCHAR(105), NCHAR(55) + NCHAR(56) + NCHAR(32) + NCHAR(71) + NCHAR(105) + NCHAR(7843) + NCHAR(105) + NCHAR(32) + NCHAR(80) + NCHAR(104) + NCHAR(243) + NCHAR(110) + NCHAR(103) + NCHAR(44) + NCHAR(32) + NCHAR(72) + NCHAR(224) + NCHAR(32) + NCHAR(78) + NCHAR(7897) + NCHAR(105), '02438693731');
INSERT INTO BENH_VIEN VALUES ('BV002', NCHAR(66) + NCHAR(7879) + NCHAR(110) + NCHAR(104) + NCHAR(32) + NCHAR(118) + NCHAR(105) + NCHAR(7879) + NCHAR(110) + NCHAR(32) + NCHAR(86) + NCHAR(105) + NCHAR(7879) + NCHAR(116) + NCHAR(32) + NCHAR(272) + NCHAR(7913) + NCHAR(99), NCHAR(52) + NCHAR(48) + NCHAR(32) + NCHAR(84) + NCHAR(114) + NCHAR(224) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(84) + NCHAR(104) + NCHAR(105) + NCHAR(44) + NCHAR(32) + NCHAR(72) + NCHAR(224) + NCHAR(32) + NCHAR(78) + NCHAR(7897) + NCHAR(105), '02438253531');
GO

INSERT INTO NHAN_VIEN VALUES ('NV001', NCHAR(78) + NCHAR(103) + NCHAR(117) + NCHAR(121) + NCHAR(7877) + NCHAR(110) + NCHAR(32) + NCHAR(68) + NCHAR(97) + NCHAR(110) + NCHAR(104) + NCHAR(32) + NCHAR(81) + NCHAR(117) + NCHAR(226) + NCHAR(110), NCHAR(81) + NCHAR(117) + NCHAR(7843) + NCHAR(110) + NCHAR(32) + NCHAR(116) + NCHAR(114) + NCHAR(7883) + NCHAR(32) + NCHAR(104) + NCHAR(7879) + NCHAR(32) + NCHAR(116) + NCHAR(104) + NCHAR(7889) + NCHAR(110) + NCHAR(103), 'admin@bloodchain.local');
INSERT INTO NHAN_VIEN VALUES ('NV002', NCHAR(72) + NCHAR(111) + NCHAR(224) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(78) + NCHAR(103) + NCHAR(7885) + NCHAR(99) + NCHAR(32) + NCHAR(84) + NCHAR(104) + NCHAR(7883) + NCHAR(110) + NCHAR(104), NCHAR(78) + NCHAR(104) + NCHAR(226) + NCHAR(110) + NCHAR(32) + NCHAR(118) + NCHAR(105) + NCHAR(234) + NCHAR(110) + NCHAR(32) + NCHAR(120) + NCHAR(233) + NCHAR(116) + NCHAR(32) + NCHAR(110) + NCHAR(103) + NCHAR(104) + NCHAR(105) + NCHAR(7879) + NCHAR(109), 'thinh@bloodchain.local');
INSERT INTO NHAN_VIEN VALUES ('NV003', NCHAR(78) + NCHAR(103) + NCHAR(244) + NCHAR(32) + NCHAR(84) + NCHAR(104) + NCHAR(7883) + NCHAR(32) + NCHAR(80) + NCHAR(104) + NCHAR(432) + NCHAR(417) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(85) + NCHAR(121) + NCHAR(234) + NCHAR(110), NCHAR(272) + NCHAR(105) + NCHAR(7873) + NCHAR(117) + NCHAR(32) + NCHAR(112) + NCHAR(104) + NCHAR(7889) + NCHAR(105) + NCHAR(32) + NCHAR(107) + NCHAR(104) + NCHAR(111) + NCHAR(32) + NCHAR(109) + NCHAR(225) + NCHAR(117), 'uyen@bloodchain.local');
INSERT INTO NHAN_VIEN VALUES ('NV004', NCHAR(78) + NCHAR(103) + NCHAR(117) + NCHAR(121) + NCHAR(7877) + NCHAR(110) + NCHAR(32) + NCHAR(84) + NCHAR(104) + NCHAR(7883) + NCHAR(32) + NCHAR(72) + NCHAR(7843) + NCHAR(105) + NCHAR(32) + NCHAR(89) + NCHAR(7871) + NCHAR(110), NCHAR(78) + NCHAR(104) + NCHAR(226) + NCHAR(110) + NCHAR(32) + NCHAR(118) + NCHAR(105) + NCHAR(234) + NCHAR(110) + NCHAR(32) + NCHAR(116) + NCHAR(105) + NCHAR(7871) + NCHAR(112) + NCHAR(32) + NCHAR(110) + NCHAR(104) + NCHAR(7853) + NCHAR(110), 'yen@bloodchain.local');
GO

INSERT INTO NGUOI_HIEN VALUES ('NH001', NCHAR(78) + NCHAR(103) + NCHAR(117) + NCHAR(121) + NCHAR(7877) + NCHAR(110) + NCHAR(32) + NCHAR(77) + NCHAR(105) + NCHAR(110) + NCHAR(104) + NCHAR(32) + NCHAR(65) + NCHAR(110) + NCHAR(104), '1998-03-12', NCHAR(78) + NCHAR(7919), '001098000111', '0912345678', NCHAR(75) + NCHAR(104) + NCHAR(244) + NCHAR(110) + NCHAR(103), 120, NCHAR(66) + NCHAR(7841) + NCHAR(99), 'A+');
INSERT INTO NGUOI_HIEN VALUES ('NH002', NCHAR(84) + NCHAR(114) + NCHAR(7847) + NCHAR(110) + NCHAR(32) + NCHAR(81) + NCHAR(117) + NCHAR(97) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(72) + NCHAR(117) + NCHAR(121), '1995-08-21', N'Nam', '001095000222', '0988123456', NCHAR(75) + NCHAR(104) + NCHAR(244) + NCHAR(110) + NCHAR(103), 240, NCHAR(86) + NCHAR(224) + NCHAR(110) + NCHAR(103), 'O+');
GO

INSERT INTO QUY_DOI_DIEM VALUES ('DQ001', NCHAR(193) + NCHAR(111) + NCHAR(32) + NCHAR(116) + NCHAR(104) + NCHAR(117) + NCHAR(110) + NCHAR(32) + NCHAR(116) + NCHAR(114) + NCHAR(105) + NCHAR(32) + NCHAR(226) + NCHAR(110), '2026-03-01 09:15:00', 50, 'NH001');
GO

INSERT INTO DANG_KY_CHIEN_DICH VALUES ('CD001', 'NH001', '2026-02-10 10:00:00');
INSERT INTO DANG_KY_CHIEN_DICH VALUES ('CD001', 'NH002', '2026-02-12 14:30:00');
INSERT INTO DANG_KY_CHIEN_DICH VALUES ('CD002', 'NH001', '2026-04-05 09:00:00');
GO

INSERT INTO VI_TRI_KHO VALUES ('VT001', NCHAR(84) + NCHAR(7911) + NCHAR(32) + NCHAR(108) + NCHAR(7841) + NCHAR(110) + NCHAR(104) + NCHAR(32) + NCHAR(65), 1);
INSERT INTO VI_TRI_KHO VALUES ('VT002', NCHAR(84) + NCHAR(7911) + NCHAR(32) + NCHAR(108) + NCHAR(7841) + NCHAR(110) + NCHAR(104) + NCHAR(32) + NCHAR(65), 2);
GO

INSERT INTO GOI_MAU_TOAN_PHAN VALUES ('GM001', '2026-02-15 09:10:00', 350, NCHAR(272) + NCHAR(7841) + NCHAR(116), 'NH001', 'A+', 'CD001', 'NV004');
INSERT INTO GOI_MAU_TOAN_PHAN VALUES ('GM002', '2026-02-15 09:45:00', 450, NCHAR(272) + NCHAR(7841) + NCHAR(116), 'NH002', 'O+', 'CD001', 'NV004');
GO

INSERT INTO KET_QUA_XET_NGHIEM VALUES ('XN001', N'HIV', NCHAR(194) + NCHAR(109) + NCHAR(32) + NCHAR(116) + NCHAR(237) + NCHAR(110) + NCHAR(104), '2026-02-15 13:30:00', 'GM001', 'NV002');
INSERT INTO KET_QUA_XET_NGHIEM VALUES ('XN002', NCHAR(86) + NCHAR(105) + NCHAR(234) + NCHAR(109) + NCHAR(32) + NCHAR(103) + NCHAR(97) + NCHAR(110) + NCHAR(32) + NCHAR(66), NCHAR(194) + NCHAR(109) + NCHAR(32) + NCHAR(116) + NCHAR(237) + NCHAR(110) + NCHAR(104), '2026-02-15 13:45:00', 'GM001', 'NV002');
GO

INSERT INTO THANH_PHAN_MAU VALUES ('TP001', NCHAR(72) + NCHAR(7891) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(99) + NCHAR(7847) + NCHAR(117), 250, '2026-03-22', NCHAR(272) + NCHAR(227) + NCHAR(32) + NCHAR(120) + NCHAR(117) + NCHAR(7845) + NCHAR(116), 'GM001', 'VT001');
INSERT INTO THANH_PHAN_MAU VALUES ('TP002', NCHAR(72) + NCHAR(117) + NCHAR(121) + NCHAR(7871) + NCHAR(116) + NCHAR(32) + NCHAR(116) + NCHAR(432) + NCHAR(417) + NCHAR(110) + NCHAR(103), 100, '2026-08-15', NCHAR(83) + NCHAR(7861) + NCHAR(110) + NCHAR(32) + NCHAR(115) + NCHAR(224) + NCHAR(110) + NCHAR(103), 'GM001', 'VT002');
GO

INSERT INTO BENH_NHAN VALUES ('BN001', NCHAR(78) + NCHAR(103) + NCHAR(117) + NCHAR(121) + NCHAR(7877) + NCHAR(110) + NCHAR(32) + NCHAR(86) + NCHAR(259) + NCHAR(110) + NCHAR(32) + NCHAR(65), '1987-01-17', NCHAR(88) + NCHAR(117) + NCHAR(7845) + NCHAR(116) + NCHAR(32) + NCHAR(104) + NCHAR(117) + NCHAR(121) + NCHAR(7871) + NCHAR(116) + NCHAR(32) + NCHAR(103) + NCHAR(105) + NCHAR(7843) + NCHAR(109) + NCHAR(32) + NCHAR(116) + NCHAR(105) + NCHAR(7875) + NCHAR(117) + NCHAR(32) + NCHAR(99) + NCHAR(7847) + NCHAR(117), 'A+', 'BV001');
GO

INSERT INTO PHIEU_YEU_CAU VALUES ('YC001', '2026-02-20 08:00:00', NCHAR(84) + NCHAR(105) + NCHAR(7875) + NCHAR(117) + NCHAR(32) + NCHAR(99) + NCHAR(7847) + NCHAR(117), 50, NCHAR(272) + NCHAR(227) + NCHAR(32) + NCHAR(100) + NCHAR(117) + NCHAR(121) + NCHAR(7879) + NCHAR(116), 'BV001', 'BN001', 'A+', 'NV003');
GO

INSERT INTO PHIEU_XUAT VALUES ('PX001', '2026-02-20 10:00:00', 50, 'YC001', 'NV003');
GO

INSERT INTO CHI_TIET_XUAT VALUES ('PX001', 'TP001', NCHAR(72) + NCHAR(242) + NCHAR(97) + NCHAR(32) + NCHAR(104) + NCHAR(7907) + NCHAR(112));
GO

CREATE FUNCTION fn_SoNgayConLai (@HanSuDung DATE)
RETURNS INT
AS
BEGIN
  RETURN DATEDIFF(day, CAST(GETDATE() AS DATE), @HanSuDung);
END;
GO

CREATE FUNCTION fn_DiemCongTheoTheTich (@TheTich INT)
RETURNS INT
AS
BEGIN
  RETURN CASE @TheTich
    WHEN 250 THEN 50
    WHEN 350 THEN 70
    WHEN 450 THEN 100
    ELSE 0
  END;
END;
GO

CREATE FUNCTION fn_XepHangThanhVien (@DiemTichLuy INT)
RETURNS NVARCHAR(20)
AS
BEGIN
  RETURN CASE
    WHEN ISNULL(@DiemTichLuy, 0) >= 200 THEN NCHAR(86) + NCHAR(224) + NCHAR(110) + NCHAR(103)
    WHEN ISNULL(@DiemTichLuy, 0) >= 100 THEN NCHAR(66) + NCHAR(7841) + NCHAR(99)
    ELSE NCHAR(272) + NCHAR(7891) + NCHAR(110) + NCHAR(103)
  END;
END;
GO

CREATE FUNCTION fn_KiemTraThanhPhanKhaDung (@MaThanhPhan VARCHAR(20))
RETURNS BIT
AS
BEGIN
  DECLARE @HopLe BIT = 0;

  IF EXISTS (
    SELECT 1
    FROM THANH_PHAN_MAU tp
    WHERE tp.MaThanhPhan = @MaThanhPhan
      AND tp.TrangThai = NCHAR(83) + NCHAR(7861) + NCHAR(110) + NCHAR(32) + NCHAR(115) + NCHAR(224) + NCHAR(110) + NCHAR(103)
      AND tp.HanSuDung >= CAST(GETDATE() AS DATE)
      AND NOT EXISTS (
        SELECT 1
        FROM CHI_TIET_XUAT ctx
        WHERE ctx.MaThanhPhan = tp.MaThanhPhan
      )
  )
  BEGIN
    SET @HopLe = 1;
  END

  RETURN @HopLe;
END;
GO

CREATE VIEW vw_TonKhoMau AS
SELECT
  g.MaNhomMau AS bloodGroup,
  g.TenNhomMau AS bloodGroupName,
  SUM(CASE WHEN tp.MaThanhPhan IS NOT NULL AND CHARINDEX(NCHAR(72) + NCHAR(7891) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(99) + NCHAR(7847) + NCHAR(117), tp.LoaiThanhPhan) > 0 THEN 1 ELSE 0 END) AS redCells,
  SUM(CASE WHEN tp.MaThanhPhan IS NOT NULL AND CHARINDEX(NCHAR(72) + NCHAR(117) + NCHAR(121) + NCHAR(7871) + NCHAR(116), tp.LoaiThanhPhan) > 0 THEN 1 ELSE 0 END) AS plasma,
  SUM(CASE WHEN tp.MaThanhPhan IS NOT NULL AND CHARINDEX(NCHAR(84) + NCHAR(105) + NCHAR(7875) + NCHAR(117), tp.LoaiThanhPhan) > 0 THEN 1 ELSE 0 END) AS platelets,
  COUNT(tp.MaThanhPhan) AS total,
  ISNULL(SUM(tp.TheTichThucTe), 0) AS totalVolume
FROM NHOM_MAU g
LEFT JOIN GOI_MAU_TOAN_PHAN gm ON gm.MaNhomMau = g.MaNhomMau
LEFT JOIN THANH_PHAN_MAU tp
  ON tp.MaGoiMau = gm.MaGoiMau
  AND dbo.fn_KiemTraThanhPhanKhaDung(tp.MaThanhPhan) = 1
GROUP BY g.MaNhomMau, g.TenNhomMau;
GO

CREATE VIEW vw_MauSapHetHan AS
SELECT
  tp.MaThanhPhan AS id,
  tp.LoaiThanhPhan AS type,
  tp.TheTichThucTe AS volume,
  tp.HanSuDung AS expiresAt,
  dbo.fn_SoNgayConLai(tp.HanSuDung) AS daysLeft,
  tp.TrangThai AS status,
  gm.MaGoiMau AS bloodBagId,
  gm.MaNhomMau AS bloodGroup,
  nh.MaNguoiHien AS donorId,
  nh.HoTen AS donorName,
  vt.MaViTri AS storageId,
  vt.TenTu + N' - Ngan ' + CAST(vt.Ngan AS NVARCHAR(10)) AS storageName
FROM THANH_PHAN_MAU tp
JOIN GOI_MAU_TOAN_PHAN gm ON gm.MaGoiMau = tp.MaGoiMau
LEFT JOIN NGUOI_HIEN nh ON nh.MaNguoiHien = gm.MaNguoiHien
LEFT JOIN VI_TRI_KHO vt ON vt.MaViTri = tp.MaViTri
WHERE dbo.fn_SoNgayConLai(tp.HanSuDung) <= 30
  AND tp.TrangThai <> NCHAR(272) + NCHAR(227) + NCHAR(32) + NCHAR(120) + NCHAR(117) + NCHAR(7845) + NCHAR(116)
  AND NOT EXISTS (
    SELECT 1
    FROM CHI_TIET_XUAT ctx
    WHERE ctx.MaThanhPhan = tp.MaThanhPhan
  );
GO

CREATE VIEW vw_PhieuYeuCauChiTiet AS
SELECT
  yc.MaPhieuYC AS id,
  yc.NgayYeuCau AS requestedAt,
  yc.LoaiThanhPhanCan AS componentType,
  yc.SoLuongML AS volume,
  yc.TrangThaiDuyet AS status,
  yc.MaBV AS hospitalId,
  bv.TenBV AS hospitalName,
  yc.MaBenhNhan AS patientId,
  bn.HoTen AS patientName,
  yc.MaNhomMau AS bloodGroup,
  yc.MaNV_Duyet AS approverId,
  nv.HoTen AS approverName
FROM PHIEU_YEU_CAU yc
LEFT JOIN BENH_VIEN bv ON bv.MaBV = yc.MaBV
LEFT JOIN BENH_NHAN bn ON bn.MaBenhNhan = yc.MaBenhNhan
LEFT JOIN NHAN_VIEN nv ON nv.MaNV = yc.MaNV_Duyet;
GO

CREATE VIEW vw_XuatKhoChiTiet AS
SELECT
  px.MaPhieuXuat AS id,
  px.NgayXuat AS exportedAt,
  px.TongTheTich AS totalVolume,
  px.MaPhieuYC AS requestId,
  yc.MaBV AS hospitalId,
  bv.TenBV AS hospitalName,
  yc.MaBenhNhan AS patientId,
  bn.HoTen AS patientName,
  yc.MaNhomMau AS bloodGroup,
  px.MaNV_Xuat AS staffId,
  nv.HoTen AS staffName,
  STUFF((
    SELECT ', ' + ctx2.MaThanhPhan
    FROM CHI_TIET_XUAT ctx2
    WHERE ctx2.MaPhieuXuat = px.MaPhieuXuat
    FOR XML PATH(''), TYPE
  ).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS componentId,
  STUFF((
    SELECT ', ' + tp2.LoaiThanhPhan
    FROM CHI_TIET_XUAT ctx2
    JOIN THANH_PHAN_MAU tp2 ON tp2.MaThanhPhan = ctx2.MaThanhPhan
    WHERE ctx2.MaPhieuXuat = px.MaPhieuXuat
    FOR XML PATH(''), TYPE
  ).value('.', 'NVARCHAR(MAX)'), 1, 2, '') AS componentType,
  (
    SELECT TOP 1 ctx3.KetQuaPhanUngCheo
    FROM CHI_TIET_XUAT ctx3
    WHERE ctx3.MaPhieuXuat = px.MaPhieuXuat
    ORDER BY ctx3.MaThanhPhan
  ) AS crossMatch
FROM PHIEU_XUAT px
LEFT JOIN PHIEU_YEU_CAU yc ON yc.MaPhieuYC = px.MaPhieuYC
LEFT JOIN BENH_VIEN bv ON bv.MaBV = yc.MaBV
LEFT JOIN BENH_NHAN bn ON bn.MaBenhNhan = yc.MaBenhNhan
LEFT JOIN NHAN_VIEN nv ON nv.MaNV = px.MaNV_Xuat;
GO

CREATE TRIGGER trg_Check_TachChiet
ON THANH_PHAN_MAU
AFTER INSERT, UPDATE
AS
BEGIN
  SET NOCOUNT ON;

  IF EXISTS (
    SELECT 1
    FROM inserted i
    JOIN GOI_MAU_TOAN_PHAN gm ON gm.MaGoiMau = i.MaGoiMau
    WHERE gm.TrangThaiKiemDinh <> NCHAR(272) + NCHAR(7841) + NCHAR(116)
       OR EXISTS (
        SELECT 1
        FROM KET_QUA_XET_NGHIEM xn
        WHERE xn.MaGoiMau = i.MaGoiMau
          AND xn.KetQua = NCHAR(68) + NCHAR(432) + NCHAR(417) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(116) + NCHAR(237) + NCHAR(110) + NCHAR(104)
      )
  )
  BEGIN
    ROLLBACK TRANSACTION;
    THROW 50001, 'Goi mau khong phu hop de tach.', 1;
  END
END;
GO

CREATE TRIGGER trg_SetHanSuDung
ON THANH_PHAN_MAU
AFTER INSERT, UPDATE
AS
BEGIN
  SET NOCOUNT ON;

  IF TRIGGER_NESTLEVEL() > 1 RETURN;

  UPDATE tp
  SET HanSuDung =
    CASE
      WHEN CHARINDEX(NCHAR(72) + NCHAR(7891) + NCHAR(110) + NCHAR(103) + NCHAR(32) + NCHAR(99) + NCHAR(7847) + NCHAR(117), i.LoaiThanhPhan) > 0
        THEN DATEADD(day, 35, CAST(gm.NgayHien AS DATE))
      WHEN CHARINDEX(NCHAR(84) + NCHAR(105) + NCHAR(7875) + NCHAR(117), i.LoaiThanhPhan) > 0
        THEN DATEADD(day, 10, CAST(gm.NgayHien AS DATE))
      WHEN CHARINDEX(NCHAR(72) + NCHAR(117) + NCHAR(121) + NCHAR(7871) + NCHAR(116), i.LoaiThanhPhan) > 0
        THEN DATEADD(day, 365, CAST(gm.NgayHien AS DATE))
      ELSE tp.HanSuDung
    END
  FROM THANH_PHAN_MAU tp
  JOIN inserted i ON i.MaThanhPhan = tp.MaThanhPhan
  JOIN GOI_MAU_TOAN_PHAN gm ON gm.MaGoiMau = i.MaGoiMau;
END;
GO

CREATE TRIGGER trg_Check_XuatMau
ON CHI_TIET_XUAT
INSTEAD OF INSERT
AS
BEGIN
  SET NOCOUNT ON;

  IF EXISTS (
    SELECT 1
    FROM inserted i
    WHERE dbo.fn_KiemTraThanhPhanKhaDung(i.MaThanhPhan) = 0
  )
  BEGIN
    ROLLBACK TRANSACTION;
    THROW 50002, 'Thanh phan mau khong san sang hoac da het han.', 1;
  END

  IF EXISTS (
    SELECT 1
    FROM inserted
    GROUP BY MaThanhPhan
    HAVING COUNT(*) > 1
  )
  BEGIN
    ROLLBACK TRANSACTION;
    THROW 50003, 'Mot thanh phan mau khong the xuat nhieu lan trong cung mot lan ghi.', 1;
  END

  INSERT INTO CHI_TIET_XUAT (MaPhieuXuat, MaThanhPhan, KetQuaPhanUngCheo)
  SELECT MaPhieuXuat, MaThanhPhan, KetQuaPhanUngCheo
  FROM inserted;
END;
GO

CREATE TRIGGER trg_UpdateTrangThaiSauXuat
ON CHI_TIET_XUAT
AFTER INSERT
AS
BEGIN
  SET NOCOUNT ON;

  UPDATE tp
  SET TrangThai = NCHAR(272) + NCHAR(227) + NCHAR(32) + NCHAR(120) + NCHAR(117) + NCHAR(7845) + NCHAR(116)
  FROM THANH_PHAN_MAU tp
  JOIN inserted i ON i.MaThanhPhan = tp.MaThanhPhan;
END;
GO

CREATE TRIGGER trg_CongDiem
ON GOI_MAU_TOAN_PHAN
AFTER INSERT
AS
BEGIN
  SET NOCOUNT ON;

  UPDATE nh
  SET DiemTichLuy = ISNULL(nh.DiemTichLuy, 0) + diem.DiemCong
  FROM NGUOI_HIEN nh
  JOIN (
    SELECT
      MaNguoiHien,
      SUM(dbo.fn_DiemCongTheoTheTich(TheTich)) AS DiemCong
    FROM inserted
    WHERE MaNguoiHien IS NOT NULL
    GROUP BY MaNguoiHien
  ) diem ON diem.MaNguoiHien = nh.MaNguoiHien;
END;
GO

CREATE TRIGGER trg_TruDiem
ON GOI_MAU_TOAN_PHAN
AFTER DELETE
AS
BEGIN
  SET NOCOUNT ON;

  -- Doi xung voi trg_CongDiem: khi xoa goi mau, tru lai dung so diem da cong
  -- (theo the tich), khong cho am. trg_UpdateHang se tu tinh lai hang.
  UPDATE nh
  SET DiemTichLuy =
    CASE
      WHEN ISNULL(nh.DiemTichLuy, 0) > diem.DiemTru THEN nh.DiemTichLuy - diem.DiemTru
      ELSE 0
    END
  FROM NGUOI_HIEN nh
  JOIN (
    SELECT
      MaNguoiHien,
      SUM(dbo.fn_DiemCongTheoTheTich(TheTich)) AS DiemTru
    FROM deleted
    WHERE MaNguoiHien IS NOT NULL
    GROUP BY MaNguoiHien
  ) diem ON diem.MaNguoiHien = nh.MaNguoiHien;
END;
GO

CREATE TRIGGER trg_UpdateHang
ON NGUOI_HIEN
AFTER INSERT, UPDATE
AS
BEGIN
  SET NOCOUNT ON;

  IF NOT UPDATE(DiemTichLuy) RETURN;

  UPDATE nh
  SET HangThanhVien = dbo.fn_XepHangThanhVien(nh.DiemTichLuy)
  FROM NGUOI_HIEN nh
  JOIN inserted i ON i.MaNguoiHien = nh.MaNguoiHien;
END;
GO
